### ISSUE TITLE
Awesome work really! Was there a "lighting_frag_SSS.frag" shader file before compiled to SPIR-V?

### ISSUE THREAD

**Issue by disini** [DoerriesT/Separable-Subsurface-Scattering-Demo#1]
Awesome work really Mr. Doerries! Much appreciated for sharing this Demo and source code, 
but was there a "lighting_frag_SSS.frag" shader source file before compiled to SPIR-V? I can't find it now Mr. Doerries, I really want to see how does the SSS implemented in the fragment shader, was it deleted or what? 
Will you please adding it again into the codes? Thank you so much sir!
Best wished!
![image](https://user-images.githubusercontent.com/5233769/99503227-0553d200-29b9-11eb-9b4e-40b8e81410a5.png)

**Comment by DoerriesT** [comment]
If you check the compile.bat file, you will see that the lighting_frag.frag file is compiled to both lighting_frag.spv and lighting_frag_SSS.spv. The latter is the same shader but with the SSS macro defined. Defining this macro causes the diffuse and specular light to be written into separate attachments, so that the diffuse lighting can be blurred by the subsurface scattering effect.

So if it wasnt clear, the basic idea behind the technique goes like this:
1) Compute lighting and store diffuse and specular lighting in separate textures.
2) Blur diffuse lighting texture with separable subsurface scattering kernel
3) Add diffuse and specular textures to get the final result.

I hope this makes it clear.

**Comment by disini** [comment]
Thanks a lot sir! Sorry for carelessness. ^_^
